import localFont from "next/font/local"

import "./globals.css";

import { Metadata } from "next";

const geistSans = localFont({
  src: "./fonts/slick.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/slick.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="fr">
      <link rel="manifest" href="/manifest.json" />
      <body
        className={` ${geistSans.variable} ${geistMono.variable}  w-full h-full bg-background antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
